sudo: false
language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --no-dev
  - php -r "copy('.env.example', '.env');"

script: vendor/bin/phpunit
